// Generated by Bisonc++ V4.05.00 on Thu, 14 Jan 2016 01:54:18 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {306, 4}, // 1: start ->  prefp declarationblock statementblock postp
     {307, 2}, // 2: prefp (PROGRAM) ->  PROGRAM IDENTIFIER
     {308, 1}, // 3: postp (PROGRAMVEGE) ->  PROGRAMVEGE
     {309, 0}, // 4: declarationblock ->  <empty>
     {309, 2}, // 5: declarationblock (VALTOZOK) ->  VALTOZOK declarationlist
     {310, 1}, // 6: declarationlist ->  declaration
     {310, 2}, // 7: declarationlist ->  declaration declarationlist
     {311, 2}, // 8: declaration (EGESZ) ->  EGESZ IDENTIFIER
     {311, 2}, // 9: declaration (LOGIKAI) ->  LOGIKAI IDENTIFIER
     {311, 2}, // 10: declaration (IDO) ->  IDO IDENTIFIER
     {312, 2}, // 11: statementblock (UTASITASOK) ->  UTASITASOK statementlist
     {313, 1}, // 12: statementlist ->  statement
     {313, 2}, // 13: statementlist ->  statement statementlist
     {314, 1}, // 14: statement (SKIP) ->  SKIP
     {314, 1}, // 15: statement ->  assignment
     {314, 1}, // 16: statement ->  cread
     {314, 1}, // 17: statement ->  cwrite
     {314, 1}, // 18: statement ->  loop
     {314, 1}, // 19: statement ->  conditional
     {315, 3}, // 20: assignment (IDENTIFIER) ->  IDENTIFIER ASSIGN expression
     {316, 2}, // 21: cread (BE) ->  BE IDENTIFIER
     {317, 2}, // 22: cwrite (KI) ->  KI expression
     {318, 5}, // 23: loop (CIKLUS) ->  CIKLUS AMIG expression statementlist CIKLUSVEGE
     {319, 5}, // 24: conditional (HA) ->  HA expression AKKOR statementlist HAVEGE
     {319, 7}, // 25: conditional (HA) ->  HA expression AKKOR statementlist KULONBEN statementlist HAVEGE
     {320, 1}, // 26: expression (IDENTIFIER) ->  IDENTIFIER
     {320, 1}, // 27: expression (NATURAL) ->  NATURAL
     {320, 1}, // 28: expression (TIME) ->  TIME
     {320, 4}, // 29: expression (HOUR) ->  HOUR LBRACE expression RBRACE
     {320, 4}, // 30: expression (MINUTE) ->  MINUTE LBRACE expression RBRACE
     {320, 1}, // 31: expression (IGAZ) ->  IGAZ
     {320, 1}, // 32: expression (HAMIS) ->  HAMIS
     {320, 3}, // 33: expression (LBRACE) ->  LBRACE expression RBRACE
     {320, 2}, // 34: expression (NEM) ->  NEM expression
     {320, 3}, // 35: expression (EQUAL) ->  expression EQUAL expression
     {320, 3}, // 36: expression (PLUS) ->  expression PLUS expression
     {320, 3}, // 37: expression (MOD) ->  expression MOD expression
     {320, 3}, // 38: expression (DIVIDE) ->  expression DIVIDE expression
     {320, 3}, // 39: expression (MULTIPLY) ->  expression MULTIPLY expression
     {320, 3}, // 40: expression (ES) ->  expression ES expression
     {320, 3}, // 41: expression (VAGY) ->  expression VAGY expression
     {320, 3}, // 42: expression (LESS) ->  expression LESS expression
     {320, 3}, // 43: expression (GREATER) ->  expression GREATER expression
     {321, 1}, // 44: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 4} },           
    { {       306}, { 1} }, // start  
    { {       307}, { 2} }, // prefp  
    { {       261}, { 3} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  3} },                    
    { {     309}, {  4} }, // declarationblock
    { {     262}, {  5} }, // VALTOZOK        
    { {       0}, { -4} },                    
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },              
    { {       280}, { 6} }, // IDENTIFIER
    { {         0}, { 0} },              
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 3} },                  
    { {       312}, { 7} }, // statementblock
    { {       263}, { 8} }, // UTASITASOK    
    { {         0}, { 0} },                  
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  6} },                   
    { {       310}, {  9} }, // declarationlist
    { {       311}, { 10} }, // declaration    
    { {       275}, { 11} }, // EGESZ          
    { {       276}, { 12} }, // LOGIKAI        
    { {       274}, { 13} }, // IDO            
    { {         0}, {  0} },                   
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  3} },               
    { {       308}, { 14} }, // postp      
    { {       264}, { 15} }, // PROGRAMVEGE
    { {         0}, {  0} },               
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 14} },                 
    { {       313}, { 16} }, // statementlist
    { {       314}, { 17} }, // statement    
    { {       283}, { 18} }, // SKIP         
    { {       315}, { 19} }, // assignment   
    { {       316}, { 20} }, // cread        
    { {       317}, { 21} }, // cwrite       
    { {       318}, { 22} }, // loop         
    { {       319}, { 23} }, // conditional  
    { {       280}, { 24} }, // IDENTIFIER   
    { {       272}, { 25} }, // BE           
    { {       273}, { 26} }, // KI           
    { {       269}, { 27} }, // CIKLUS       
    { {       265}, { 28} }, // HA           
    { {         0}, {  0} },                 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_10[] =
{
    { { REQ_DEF}, {  6} },                   
    { {     310}, { 29} }, // declarationlist
    { {     311}, { 10} }, // declaration    
    { {     275}, { 11} }, // EGESZ          
    { {     276}, { 12} }, // LOGIKAI        
    { {     274}, { 13} }, // IDO            
    { {       0}, { -6} },                   
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       280}, { 30} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       280}, { 31} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       280}, { 32} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_14[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_17[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     313}, {  33} }, // statementlist
    { {     314}, {  17} }, // statement    
    { {     283}, {  18} }, // SKIP         
    { {     315}, {  19} }, // assignment   
    { {     316}, {  20} }, // cread        
    { {     317}, {  21} }, // cwrite       
    { {     318}, {  22} }, // loop         
    { {     319}, {  23} }, // conditional  
    { {     280}, {  24} }, // IDENTIFIER   
    { {     272}, {  25} }, // BE           
    { {     273}, {  26} }, // KI           
    { {     269}, {  27} }, // CIKLUS       
    { {     265}, {  28} }, // HA           
    { {       0}, { -12} },                 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       277}, { 34} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       280}, { 35} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 36} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       270}, { 46} }, // AMIG
    { {         0}, {  0} },        
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 47} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 48} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_36[] =
{
    { { REQ_DEF}, {  10} },            
    { {     287}, {  49} }, // EQUAL   
    { {     290}, {  50} }, // PLUS    
    { {     293}, {  51} }, // MOD     
    { {     292}, {  52} }, // DIVIDE  
    { {     291}, {  53} }, // MULTIPLY
    { {     285}, {  54} }, // ES      
    { {     284}, {  55} }, // VAGY    
    { {     288}, {  56} }, // LESS    
    { {     289}, {  57} }, // GREATER 
    { {       0}, { -22} },            
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       278}, { 58} }, // LBRACE
    { {         0}, {  0} },          
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       278}, { 59} }, // LBRACE
    { {         0}, {  0} },          
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 60} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 61} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 62} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 11} },            
    { {       266}, { 63} }, // AKKOR   
    { {       287}, { 49} }, // EQUAL   
    { {       290}, { 50} }, // PLUS    
    { {       293}, { 51} }, // MOD     
    { {       292}, { 52} }, // DIVIDE  
    { {       291}, { 53} }, // MULTIPLY
    { {       285}, { 54} }, // ES      
    { {       284}, { 55} }, // VAGY    
    { {       288}, { 56} }, // LESS    
    { {       289}, { 57} }, // GREATER 
    { {         0}, {  0} },            
};

SR__ s_48[] =
{
    { { REQ_DEF}, {  10} },            
    { {     287}, {  49} }, // EQUAL   
    { {     290}, {  50} }, // PLUS    
    { {     293}, {  51} }, // MOD     
    { {     292}, {  52} }, // DIVIDE  
    { {     291}, {  53} }, // MULTIPLY
    { {     285}, {  54} }, // ES      
    { {     284}, {  55} }, // VAGY    
    { {     288}, {  56} }, // LESS    
    { {     289}, {  57} }, // GREATER 
    { {       0}, { -20} },            
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 64} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 65} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 66} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 67} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 68} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 69} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 70} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 71} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 72} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 73} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       320}, { 74} }, // expression
    { {       280}, { 37} }, // IDENTIFIER
    { {       257}, { 38} }, // NATURAL   
    { {       258}, { 39} }, // TIME      
    { {       259}, { 40} }, // HOUR      
    { {       260}, { 41} }, // MINUTE    
    { {       281}, { 42} }, // IGAZ      
    { {       282}, { 43} }, // HAMIS     
    { {       278}, { 44} }, // LBRACE    
    { {       286}, { 45} }, // NEM       
    { {         0}, {  0} },              
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, { 11} },            
    { {       279}, { 75} }, // RBRACE  
    { {       287}, { 49} }, // EQUAL   
    { {       290}, { 50} }, // PLUS    
    { {       293}, { 51} }, // MOD     
    { {       292}, { 52} }, // DIVIDE  
    { {       291}, { 53} }, // MULTIPLY
    { {       285}, { 54} }, // ES      
    { {       284}, { 55} }, // VAGY    
    { {       288}, { 56} }, // LESS    
    { {       289}, { 57} }, // GREATER 
    { {         0}, {  0} },            
};

SR__ s_61[] =
{
    { { REQ_DEF}, {   8} },            
    { {     287}, {  49} }, // EQUAL   
    { {     290}, {  50} }, // PLUS    
    { {     293}, {  51} }, // MOD     
    { {     292}, {  52} }, // DIVIDE  
    { {     291}, {  53} }, // MULTIPLY
    { {     288}, {  56} }, // LESS    
    { {     289}, {  57} }, // GREATER 
    { {       0}, { -34} },            
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 23} },                 
    { {       313}, { 76} }, // statementlist
    { {       287}, { 49} }, // EQUAL        
    { {       290}, { 50} }, // PLUS         
    { {       293}, { 51} }, // MOD          
    { {       292}, { 52} }, // DIVIDE       
    { {       291}, { 53} }, // MULTIPLY     
    { {       285}, { 54} }, // ES           
    { {       284}, { 55} }, // VAGY         
    { {       288}, { 56} }, // LESS         
    { {       289}, { 57} }, // GREATER      
    { {       314}, { 17} }, // statement    
    { {       283}, { 18} }, // SKIP         
    { {       315}, { 19} }, // assignment   
    { {       316}, { 20} }, // cread        
    { {       317}, { 21} }, // cwrite       
    { {       318}, { 22} }, // loop         
    { {       319}, { 23} }, // conditional  
    { {       280}, { 24} }, // IDENTIFIER   
    { {       272}, { 25} }, // BE           
    { {       273}, { 26} }, // KI           
    { {       269}, { 27} }, // CIKLUS       
    { {       265}, { 28} }, // HA           
    { {         0}, {  0} },                 
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 14} },                 
    { {       313}, { 77} }, // statementlist
    { {       314}, { 17} }, // statement    
    { {       283}, { 18} }, // SKIP         
    { {       315}, { 19} }, // assignment   
    { {       316}, { 20} }, // cread        
    { {       317}, { 21} }, // cwrite       
    { {       318}, { 22} }, // loop         
    { {       319}, { 23} }, // conditional  
    { {       280}, { 24} }, // IDENTIFIER   
    { {       272}, { 25} }, // BE           
    { {       273}, { 26} }, // KI           
    { {       269}, { 27} }, // CIKLUS       
    { {       265}, { 28} }, // HA           
    { {         0}, {  0} },                 
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   7} },            
    { {     290}, {  50} }, // PLUS    
    { {     293}, {  51} }, // MOD     
    { {     292}, {  52} }, // DIVIDE  
    { {     291}, {  53} }, // MULTIPLY
    { {     288}, {  56} }, // LESS    
    { {     289}, {  57} }, // GREATER 
    { {       0}, { -35} },            
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   4} },            
    { {     293}, {  51} }, // MOD     
    { {     292}, {  52} }, // DIVIDE  
    { {     291}, {  53} }, // MULTIPLY
    { {       0}, { -36} },            
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   8} },            
    { {     287}, {  49} }, // EQUAL   
    { {     290}, {  50} }, // PLUS    
    { {     293}, {  51} }, // MOD     
    { {     292}, {  52} }, // DIVIDE  
    { {     291}, {  53} }, // MULTIPLY
    { {     288}, {  56} }, // LESS    
    { {     289}, {  57} }, // GREATER 
    { {       0}, { -40} },            
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   9} },            
    { {     287}, {  49} }, // EQUAL   
    { {     290}, {  50} }, // PLUS    
    { {     293}, {  51} }, // MOD     
    { {     292}, {  52} }, // DIVIDE  
    { {     291}, {  53} }, // MULTIPLY
    { {     285}, {  54} }, // ES      
    { {     288}, {  56} }, // LESS    
    { {     289}, {  57} }, // GREATER 
    { {       0}, { -41} },            
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   5} },            
    { {     290}, {  50} }, // PLUS    
    { {     293}, {  51} }, // MOD     
    { {     292}, {  52} }, // DIVIDE  
    { {     291}, {  53} }, // MULTIPLY
    { {       0}, { -42} },            
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   5} },            
    { {     290}, {  50} }, // PLUS    
    { {     293}, {  51} }, // MOD     
    { {     292}, {  52} }, // DIVIDE  
    { {     291}, {  53} }, // MULTIPLY
    { {       0}, { -43} },            
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 11} },            
    { {       279}, { 78} }, // RBRACE  
    { {       287}, { 49} }, // EQUAL   
    { {       290}, { 50} }, // PLUS    
    { {       293}, { 51} }, // MOD     
    { {       292}, { 52} }, // DIVIDE  
    { {       291}, { 53} }, // MULTIPLY
    { {       285}, { 54} }, // ES      
    { {       284}, { 55} }, // VAGY    
    { {       288}, { 56} }, // LESS    
    { {       289}, { 57} }, // GREATER 
    { {         0}, {  0} },            
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 11} },            
    { {       279}, { 79} }, // RBRACE  
    { {       287}, { 49} }, // EQUAL   
    { {       290}, { 50} }, // PLUS    
    { {       293}, { 51} }, // MOD     
    { {       292}, { 52} }, // DIVIDE  
    { {       291}, { 53} }, // MULTIPLY
    { {       285}, { 54} }, // ES      
    { {       284}, { 55} }, // VAGY    
    { {       288}, { 56} }, // LESS    
    { {       289}, { 57} }, // GREATER 
    { {         0}, {  0} },            
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       271}, { 80} }, // CIKLUSVEGE
    { {         0}, {  0} },              
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       268}, { 81} }, // HAVEGE  
    { {       267}, { 82} }, // KULONBEN
    { {         0}, {  0} },            
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, { 14} },                 
    { {       313}, { 83} }, // statementlist
    { {       314}, { 17} }, // statement    
    { {       283}, { 18} }, // SKIP         
    { {       315}, { 19} }, // assignment   
    { {       316}, { 20} }, // cread        
    { {       317}, { 21} }, // cwrite       
    { {       318}, { 22} }, // loop         
    { {       319}, { 23} }, // conditional  
    { {       280}, { 24} }, // IDENTIFIER   
    { {       272}, { 25} }, // BE           
    { {       273}, { 26} }, // KI           
    { {       269}, { 27} }, // CIKLUS       
    { {       265}, { 28} }, // HA           
    { {         0}, {  0} },                 
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       268}, { 84} }, // HAVEGE
    { {         0}, {  0} },          
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 68 "bplang.y"
        {
         std::cout << std::string("") +
         "global main\n"
         "extern be_egesz\n" +
         "extern be_logikai\n" +
         "extern ki_egesz\n" +
         "extern ki_logikai\n" +
         d_vsp__[-2].instr->code +
         d_vsp__[-1].instr->code +
         "ret\n";
         delete d_vsp__[-2].instr;
         delete d_vsp__[-1].instr;
         }
        break;

        case 2:
#line 88 "bplang.y"
        {
         delete d_vsp__[0].text;
         }
        break;

        case 3:
#line 95 "bplang.y"
        {
         }
        break;

        case 4:
#line 101 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_loc__.first_line, "");
         }
        break;

        case 5:
#line 106 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[0].instr->line, "\nsection .data\n" + d_vsp__[0].instr->code);
         delete d_vsp__[0].instr;
         }
        break;

        case 6:
#line 114 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[0].instr->line, d_vsp__[0].instr->code);
         delete d_vsp__[0].instr;
         }
        break;

        case 7:
#line 120 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[-1].instr->line, d_vsp__[-1].instr->code + d_vsp__[0].instr->code);
         delete d_vsp__[-1].instr;
         delete d_vsp__[0].instr;
         }
        break;

        case 8:
#line 129 "bplang.y"
        {
         if( symbols.count(*d_vsp__[0].text) > 0 )
         {
         std::stringstream ss;
         ss << *d_vsp__[0].text << " is already declared as a variable at line " << symbols[*d_vsp__[0].text].line << ".";
         error( ss.str().c_str() );
         }
         symbols[*d_vsp__[0].text] = expr_decl( d_loc__.first_line, Natural,
         *d_vsp__[0].text + ": dd 0\n"
         );
         d_val__.instr = new instr_decl(symbols[*d_vsp__[0].text].line, symbols[*d_vsp__[0].text].code);
         delete d_vsp__[0].text;
         }
        break;

        case 9:
#line 147 "bplang.y"
        {
         if( symbols.count(*d_vsp__[0].text) > 0 )
         {
         std::stringstream ss;
         ss << *d_vsp__[0].text << " is already declared as a variable at line " << symbols[*d_vsp__[0].text].line << ".";
         error( ss.str().c_str() );
         }
         symbols[*d_vsp__[0].text] = expr_decl( d_loc__.first_line, Bool, 
         *d_vsp__[0].text + ": db 0\n"
         );
         d_val__.instr = new instr_decl(symbols[*d_vsp__[0].text].line, symbols[*d_vsp__[0].text].code);
         delete d_vsp__[0].text;
         }
        break;

        case 10:
#line 165 "bplang.y"
        {
         if( symbols.count(*d_vsp__[0].text) > 0 )
         {
         std::stringstream ss;
         ss << *d_vsp__[0].text << " is already declared as a variable at line " << symbols[*d_vsp__[0].text].line << ".";
         error( ss.str().c_str() );
         }
         symbols[*d_vsp__[0].text] = expr_decl( d_loc__.first_line, Time, 
         *d_vsp__[0].text + ": dd 0\n"
         );
         d_val__.instr = new instr_decl(symbols[*d_vsp__[0].text].line, symbols[*d_vsp__[0].text].code);
         delete d_vsp__[0].text;
         }
        break;

        case 11:
#line 185 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[0].instr->line,
         "\nsection .text\nmain:\n" +
         d_vsp__[0].instr->code
         );
         delete d_vsp__[0].instr;
         }
        break;

        case 12:
#line 196 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[0].instr->line, d_vsp__[0].instr->code);
         delete d_vsp__[0].instr;
         }
        break;

        case 13:
#line 202 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[-1].instr->line, d_vsp__[-1].instr->code + d_vsp__[0].instr->code);
         delete d_vsp__[-1].instr;
         delete d_vsp__[0].instr;
         }
        break;

        case 14:
#line 212 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_loc__.first_line, "");
         }
        break;

        case 15:
#line 217 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[0].instr->line, d_vsp__[0].instr->code);
         delete d_vsp__[0].instr;
         }
        break;

        case 16:
#line 224 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[0].instr->line, d_vsp__[0].instr->code);
         delete d_vsp__[0].instr;
         }
        break;

        case 17:
#line 231 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[0].instr->line, d_vsp__[0].instr->code);
         delete d_vsp__[0].instr;
         }
        break;

        case 18:
#line 238 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[0].instr->line, d_vsp__[0].instr->code);
         delete d_vsp__[0].instr;
         }
        break;

        case 19:
#line 245 "bplang.y"
        {
         d_val__.instr = new instr_decl(d_vsp__[0].instr->line, d_vsp__[0].instr->code);
         delete d_vsp__[0].instr;
         }
        break;

        case 20:
#line 256 "bplang.y"
        {
         if( symbols.count(*d_vsp__[-2].text) == 0 )
         {
         std::stringstream ss;
         ss << "Unknown identifier: " << *d_vsp__[-2].text;
         error( ss.str().c_str() );
         }
         if( symbols[*d_vsp__[-2].text].etype != d_vsp__[0].expr->etype )
         {
         error( "Type mismatch in assignment." );
         }
         std::string reg = d_vsp__[0].expr->etype != Bool ? "eax" : "al";
         d_val__.instr = new instr_decl(d_loc__.first_line, d_vsp__[0].expr->code + "mov [" + *d_vsp__[-2].text + "], " + reg + "\n");
         delete d_vsp__[-2].text;
         delete d_vsp__[0].expr;
         }
        break;

        case 21:
#line 280 "bplang.y"
        {
         if( symbols.count(*d_vsp__[0].text) == 0 )
         {
         std::stringstream ss;
         ss << "Unknown identifier: " << *d_vsp__[0].text;
         error( ss.str().c_str() );
         }
         std::string fun = symbols[*d_vsp__[0].text].etype == Natural ? "be_egesz" : "be_logikai";
         std::string reg = symbols[*d_vsp__[0].text].etype == Natural ? "eax" : "al";
         d_val__.instr = new instr_decl(
         symbols[*d_vsp__[0].text].line,
         "call " + fun + "\n" +
         "mov [" + *d_vsp__[0].text + "], " + reg + "\n"
         );
         delete d_vsp__[0].text;
         }
        break;

        case 22:
#line 303 "bplang.y"
        {
         if (d_vsp__[0].expr->etype == Time)
         {
         error( "Time expressions cannot be printed." );
         }
         std::string fun = d_vsp__[0].expr->etype == Natural ? "ki_egesz" : "ki_logikai";
         std::string reg = d_vsp__[0].expr->etype == Bool ? "movzx eax, al\npush eax\n" : "push eax\n";
         d_val__.instr = new instr_decl(
         d_loc__.first_line,
         d_vsp__[0].expr->code +
         reg +
         "call " + fun + "\n" +
         "add esp, 4\n"
         );
         delete d_vsp__[0].expr;
         }
        break;

        case 23:
#line 326 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != Bool)
         {
         error( "Only boolean expression permitted in loop condition." );
         }
         std::stringstream ss;
         ss << "lab#" << Parser::labels++;
         std::string lstart = ss.str();
         ss.str("");
         ss << "lab#" << Parser::labels++;
         std::string lend = ss.str();
         d_val__.instr = new instr_decl(
         d_loc__.first_line,
         "\n" + lstart + ":\n" +
         d_vsp__[-2].expr->code +
         "cmp al, 1\n" +
         "jne near " + lend + "\n" +
         d_vsp__[-1].instr->code +
         "jmp " + lstart + "\n\n" +
         lend + ":\n"
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[-1].instr;
         }
        break;

        case 24:
#line 360 "bplang.y"
        {
         if (d_vsp__[-3].expr->etype != Bool)
         {
         error( "Only boolean expression permitted in if statement's condition." );
         }
         std::stringstream ss;
         ss << "lab#" << Parser::labels++;
         std::string lend = ss.str();
         d_val__.instr = new instr_decl(
         d_loc__.first_line,
         d_vsp__[-3].expr->code +
         "cmp al, 1\n" +
         "jne near " + lend + "\n" +
         d_vsp__[-1].instr->code + "\n" +
         lend + ":\n"
         );
         delete d_vsp__[-3].expr;
         delete d_vsp__[-1].instr;
         }
        break;

        case 25:
#line 385 "bplang.y"
        {
         if (d_vsp__[-5].expr->etype != Bool)
         {
         error( "Only boolean expressions permitted in if statement's condition." );
         }
         std::stringstream ss;
         ss << "lab#" << Parser::labels++;
         std::string lstart = ss.str();
         ss.str("");
         ss << "lab#" << Parser::labels++;
         std::string lelse = ss.str();
         ss.str("");
         ss << "lab#" << Parser::labels++;
         std::string lend = ss.str();
         d_val__.instr = new instr_decl(
         d_loc__.first_line,
         "\n" + lstart + ":\n" +
         d_vsp__[-5].expr->code +
         "cmp al, 1\n" +
         "jne near " + lelse + "\n" +
         d_vsp__[-3].instr->code +
         "jmp " + lend + "\n\n" +
         lelse + ":\n" +
         d_vsp__[-1].instr->code + "\n" +
         lend + ":\n"
         );
         delete d_vsp__[-5].expr;
         delete d_vsp__[-3].instr;
         delete d_vsp__[-1].instr;
         }
        break;

        case 26:
#line 426 "bplang.y"
        {
         if( symbols.count(*d_vsp__[0].text) == 0 )
         {
         std::stringstream ss;
         ss << "Unknown identifier: " << *d_vsp__[0].text;
         error( ss.str().c_str() );
         }
         std::string dest = symbols[*d_vsp__[0].text].etype != Bool ? "eax" : "al";
         d_val__.expr = new expr_decl(d_loc__.first_line, symbols[*d_vsp__[0].text].etype,
         "mov " + dest + ", [" + *d_vsp__[0].text + "]\n"
         );
         delete d_vsp__[0].text;
         }
        break;

        case 27:
#line 444 "bplang.y"
        {
         d_val__.expr = new expr_decl(d_loc__.first_line, Natural, "mov eax, " + *d_vsp__[0].text + "\n");
         delete d_vsp__[0].text;
         }
        break;

        case 28:
#line 451 "bplang.y"
        {
         d_vsp__[0].text->erase(d_vsp__[0].text->begin() + 2);
         d_val__.expr = new expr_decl(d_loc__.first_line, Time, "mov eax, " + *d_vsp__[0].text + "\n");
         delete d_vsp__[0].text;
         }
        break;

        case 29:
#line 460 "bplang.y"
        {
         if (d_vsp__[-1].expr->etype != Time)
         {
         error( "ora(Time t) can take only Time parameters." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Natural,
         d_vsp__[-1].expr->code +
         "mov edx, 0\n" +
         "mov ebx, 100\n" +
         "div ebx\n"
         );
         delete d_vsp__[-1].expr;
         }
        break;

        case 30:
#line 476 "bplang.y"
        {
         if (d_vsp__[-1].expr->etype != Time)
         {
         error( "minute(Time t) can take only Time parameters." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Natural,
         d_vsp__[-1].expr->code +
         "mov edx, 0\n" +
         "mov ebx, 100\n" +
         "div ebx\n" +
         "mov eax, edx\n"
         );
         delete d_vsp__[-1].expr;
         }
        break;

        case 31:
#line 493 "bplang.y"
        {
         d_val__.expr = new expr_decl(d_loc__.first_line, Bool,
         "mov al, 1\n"
         );
         }
        break;

        case 32:
#line 500 "bplang.y"
        {
         d_val__.expr = new expr_decl(d_loc__.first_line, Bool,
         "mov al, 0\n"
         );
         }
        break;

        case 33:
#line 507 "bplang.y"
        {
         d_val__.expr = new expr_decl(d_loc__.first_line, d_vsp__[-1].expr->etype, d_vsp__[-1].expr->code);
         delete d_vsp__[-1].expr;
         }
        break;

        case 34:
#line 514 "bplang.y"
        {
         if (d_vsp__[0].expr->etype != Bool)
         {
         error( "Only Bool expressions can be negated." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, d_vsp__[0].expr->etype, d_vsp__[0].expr->code + "xor al, 1\n");
         delete d_vsp__[0].expr;
         }
        break;

        case 35:
#line 526 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != d_vsp__[0].expr->etype)
         {
         error( "Type mismatch in equation." );
         }
         std::string regs = d_vsp__[-2].expr->etype == Natural ? "eax, ebx" : "al, bl";
         d_val__.expr = new expr_decl(d_loc__.first_line, Bool,
         d_vsp__[0].expr->code +
         "push eax\n" +
         d_vsp__[-2].expr->code +
         "pop ebx\n" +
         "cmp " + regs + "\n" +
         "sete al\n"
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 36:
#line 548 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != Natural)
         {
         error( "The first argument of + is not a EGESZ." );
         }
         if (d_vsp__[0].expr->etype != Natural)
         {
         error( "The second argument of + is not a EGESZ." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Natural,
         d_vsp__[0].expr->code +
         "push eax\n" +
         d_vsp__[-2].expr->code +
         "pop ebx\n" +
         "add eax, ebx\n"
         );
         
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 37:
#line 572 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != Natural)
         {
         error( "The first argument of MOD is not a EGESZ." );
         }
         if (d_vsp__[0].expr->etype != Natural)
         {
         error( "The second argument of MOD is not a EGESZ." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Natural,
         d_vsp__[0].expr->code +
         "push eax\n" +
         d_vsp__[-2].expr->code +
         "pop ebx\n" +
         "mov edx, 0\n" +
         "div ebx\n" +
         "mov eax, edx\n"
         );
         
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 38:
#line 598 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != Natural)
         {
         error( "The first argument of / is not a EGESZ." );
         }
         if (d_vsp__[0].expr->etype != Natural)
         {
         error( "The second argument of / is not a EGESZ." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Natural,
         d_vsp__[0].expr->code +
         "push eax\n" +
         d_vsp__[-2].expr->code +
         "pop ebx\n" +
         "mov edx, 0\n" +
         "div ebx\n"
         );
         
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 39:
#line 623 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != Natural)
         {
         error( "The first argument of * is not a EGESZ." );
         }
         if (d_vsp__[0].expr->etype != Natural)
         {
         error( "The second argument of * is not a EGESZ." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Natural,
         d_vsp__[0].expr->code +
         "push eax\n" +
         d_vsp__[-2].expr->code +
         "pop ebx\n" +
         "mul ebx\n"
         );
         
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 40:
#line 647 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != Bool)
         {
         error( "The first argument of ES is not Boolean." );
         }
         if (d_vsp__[0].expr->etype != Bool)
         {
         error( "The second argument of ES and is not Boolean." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Bool,
         d_vsp__[0].expr->code +
         "push eax\n" +
         d_vsp__[-2].expr->code +
         "pop ebx\n" +
         "and al, bl\n" 
         );
         
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 41:
#line 671 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != Bool)
         {
         error( "The first argument of OR is not Boolean." );
         }
         if (d_vsp__[0].expr->etype != Bool)
         {
         error( "The second argument of OR is not Boolean." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Bool,
         d_vsp__[0].expr->code +
         "push eax\n" +
         d_vsp__[-2].expr->code +
         "pop ebx\n" +
         "or al, bl\n" 
         );
         
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 42:
#line 695 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != Natural)
         {
         error( "The first argument of < is not a EGESZ." );
         }
         if (d_vsp__[0].expr->etype != Natural)
         {
         error( "The second argument of < is not a EGESZ." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Bool,
         d_vsp__[0].expr->code +
         "push eax\n" +
         d_vsp__[-2].expr->code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "setl al\n"
         );
         
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 43:
#line 720 "bplang.y"
        {
         if (d_vsp__[-2].expr->etype != Natural)
         {
         error( "The first argument of > is not a EGESZ." );
         }
         if (d_vsp__[0].expr->etype != Natural)
         {
         error( "The second argument of > is not a EGESZ." );
         }
         d_val__.expr = new expr_decl(d_loc__.first_line, Bool,
         d_vsp__[0].expr->code +
         "push eax\n" +
         d_vsp__[-2].expr->code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "seta al\n"
         );
         
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}




